### ISSUE TITLE
[Meta] DataPipes for PP Production Checkllist

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/ocf_datapipes#18]
Overview of what needs to be done for PP production with Datapipes

## Detailed Description

These will be made into issues, the ones that are not already done

Base steps of getting the data:

- [x] Load Satellite Data
- [x] Load NWP Data
- [x] Load GSP Data
- [x] Load Topo Data
- [x] Load Passiv PV Data
- [x] Select location in data
- [x] [Load GSP database data](https://github.com/openclimatefix/ocf_datapipes/issues/45)
- [x] https://github.com/openclimatefix/ocf_datapipes/issues/31
- [x] https://github.com/openclimatefix/ocf_datapipes/issues/30
- [x] ?Validation on data sources?In nowcasting_dataset
- [ ] Add Diagram of whats going on  to readme - https://docs.google.com/presentation/d/1JScci-Ye982vfZqxdCDF7EeuS26V5D4wYcS99KY_56o/edit#slide=id.p
- [x] Move end2end test to 'Production datapipe'. Make folder called production
- [x] https://github.com/openclimatefix/ocf_datapipes/issues/33
- [x] https://github.com/openclimatefix/ocf_datapipes/issues/34
- [x] https://github.com/openclimatefix/ocf_datapipes/issues/36
- [x] https://github.com/openclimatefix/ocf_datapipes/issues/57

Some Data Transformations that need to be done, the `xr_` and `np_batch_processors` in PP:

- [x] PVRollingWindow transform for PV data
- [x] EncodeSpaceTime
- [x] SaveT0Time
- [x] AddTopography
- [x] All timestamps have to cover history and future for `_time_utc` parts of NumpyBatch
- [x] Downsample NWPs
- [x] Normalize Data
- [x] AlignGSPTo5Min
- [x] SunPosition to add sun position
- [x] GSP and PV System IDs (potentially just set to 1)

Post Data Transform ones

- [x] Make data into NumpyBatch
- [x] Optionla to save NumpyBatch to save out

Other issues
- #24 
- #20 
- #3 
- #2 
- https://github.com/openclimatefix/ocf_datapipes/issues/38
- https://github.com/openclimatefix/ocf_datapipes/issues/39

## Possible Implementation
Right now, the majority of this is happening in #14

**Comment by jacobbieker** [comment]
SunPosition is somewhat there, just need to add the location picker to the test

NWP doesn't like the NumpyBatch at the moment, but the rest all load and form the full NumpyBatch successfully. 

Still need to figure out how to actually call the datapipes functional form, would be cleaner, although the current method still works.

**Comment by jacobbieker** [comment]
NWP target time UTC adding and selecting for the live system is a bit broken and currently a bit stuck on that. But selecting all the other data types for the live environment works in testing

**Comment by jacobbieker** [comment]
The target time now works, although does mix a bit the selecting and adding of the target time

**Comment by jacobbieker** [comment]
End2End test now works! Only missing thing is the setting system_ids to 1, and some PV filtering. For now, might put the PV filtering in the loader just to keep it a bit simpler right now, and then refactor it out as we go along

**Comment by jacobbieker** [comment]
The saving out of the data can be accomplished with the built in datapipe https://pytorch.org/data/main/generated/torchdata.datapipes.iter.FSSpecSaver.html#torchdata.datapipes.iter.FSSpecSaver

**Comment by jacobbieker** [comment]
Closing this now, as we aren't using PP
